# Copyright (c) 2025 Aaro Koinsaari
# Licensed under the Apache License, Version 2.0

services:
  updater:
    build: .
    image: map-data-updater:local
    container_name: inwheel-data-updater
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATA_DIR=/app/data
      - REGION=${REGION:-}
      - OVERWRITE=${OVERWRITE:-false}
      - TEST_MODE=${TEST_MODE:-false}
    command: ${ARGS:-}
    restart: 'no'
    networks:
      - inwheel-network

networks:
  inwheel-network:
    driver: bridge
