# Copyright (c) 2025 Aaro Koinsaari
# Licensed under the Apache License, Version 2.0

name: Update Map Data

on:
  schedule:
    # Run every Monday at 3:00 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:
    inputs:
      region:
        description: 'Specific region to update (leave empty for all)'
        required: false
      update_all:
        description: 'Force update all places, including user-modified ones'
        type: boolean
        default: false
        required: false
      test_mode:
        description: 'Test mode, only process 100 places per region'
        type: boolean
        default: false
        required: false

concurrency:
  group: data-update
  cancel-in-progress: false

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          load: true
          tags: map-data-updater:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Ensure script is executable
        run: chmod +x ./backend/scripts/run-update.sh

      - name: Run data update
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REGION: ${{ github.event.inputs.region }}
          UPDATE_ALL: ${{ github.event.inputs.update_all }}
          TEST_MODE: ${{ github.event.inputs.test_mode }}
        run: ./backend/scripts/run-update.sh

      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: update-logs
          path: ./backend/data/update.log
          retention-days: 7

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            github.rest.issues.create({
              owner,
              repo,
              title: `❌ Data update failed on ${new Date().toISOString().split('T')[0]}`,
              body: `The weekly data update workflow failed. [See the logs](https://github.com/${owner}/${repo}/actions/runs/${context.runId})`
            });
